arb-dir: lib/l10n

template-arb-file: app_en.arb

output-localization-file: app_localizations.dart

translator:
  targets:
    - en
    - ru
    - ar
    - de
    - es
    - fr
    - pt
    - zh
    
